/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    Cor corLinha = new Cor(255, 0, 0);
    Cor corPreenchimento = new Cor(0, 255, 0);

    Linha l = new Linha(corLinha, corPreenchimento, 10, 20);
}
