/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Contador contador = new Contador();

        contador.definirContador(0);
        System.out.println(contador.obterValorAtual());

        contador.incrementarContador();
        System.out.println(contador.obterValorAtual());

        contador.incrementarContador();
        System.out.println(contador.obterValorAtual());


    }
}
