/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

public class App implements DrawListener {

    private Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.addListener(this);
        this.draw.show();
    }

    @Override
    public void mousePressed(double x, double y) {

        Bandeira b = new Bandeira(.1,.5,3);

        b.desenhar(draw);

    }

    public static void main(String[] args) {

        App app = new App();


    }
}
