/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;
import java.util.InputMismatchException;
import java.util.Scanner;
public class App {

    public static void main(String[] args) {

       // Caixa<String> c = new Caixa<>();
       // String s = "Olá Mundo!";
       // c.set(s);
       // String outra = c.getDado();

        Scanner teclado = new Scanner(System.in);

        int[] vetor = new int [10];
        int numero, posicao;

        do {
            try {
                System.out.println("Entre com o número: ");
                numero = teclado.nextInt();
                break;
            } catch (InputMismatchException e) {
                System.err.println("Só é permitidos números no limite do vetor.");
                teclado.nextLine();
            }
        } while(true);
        boolean sair = true;

        
        do{
            try{
                System.out.println("Entre com posição: ");
                posicao = teclado.nextInt();
                break;
            } catch (InputMismatchException e) {
                System.err.println("Erro. forneça um numero");
                teclado.nextLine();
            } catch(ArrayIndexOutOfBoundsException e) {
                System.err.println("Forneça valores dentro do limite");
                teclado.nextLine();
            }
        } while(true);

        vetor[posicao] = numero;
    }

}
